name = "cf-worker-ws-dev"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "1b001b65-c2e5-42f2-a7bf-10e8a1f7f615"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
